spring.application.name=04-SpringBootConfigPropsEx2

my.app.id=11
my.app.code=MODEL
my.app.active=true

my.app.ldata[0]=A
my.app.ldata[1]=B
my.app.ldata[2]=C

my.app.sdata=X,Y,Z
my.app.adata=i,j,k

my.app.mdata.A1=B1
my.app.mdata.A2=B2

my.app.pdata.C1=D1
my.app.pdata.C2=D2

my.app.pob.pid=98
my.app.pob_pcode=ABC

spring.mail.host=gmail

