spring.application.name=02-SpringBootCoreInputEx
# Our own keys
# On comment: 
#	PlaceholderResolutionException: Could not resolve placeholder 'my.db.driver' in value "${my.db.driver}"
my.db.driver=Oracle
my.db.url=Oracle
my.db.user=admin
my.db.pwd=Abc1234
